
name: build and test Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Install chrome
      run:  sudo apt-get update
            sudo apt-get install -y google-chrome-stable
     
    
    - name: Restore dependencies
      run: dotnet restore SeleniumBasicExercise.sln
    - name: Build SeleniumBasicExercise
      run: dotnet build SeleniumBasicExercise.sln --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
